//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTimeSync.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoTimeSync.Labels.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking that folder &apos;{0}&apos; exists ....
        /// </summary>
        internal static string CheckFolder_CheckingFolderExists {
            get {
                return ResourceManager.GetString("CheckFolder_CheckingFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder does not exist..
        /// </summary>
        internal static string CheckFolder_SelectedFolderNotExist {
            get {
                return ResourceManager.GetString("CheckFolder_SelectedFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring folder NOK.
        /// </summary>
        internal static string ExploreFolder_ErrorConclusion {
            get {
                return ResourceManager.GetString("ExploreFolder_ErrorConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: At least 2 subfolders representing the collections to synchronise must be present inside the selected folder.
        /// </summary>
        internal static string ExploreFolder_ErrorExplanationInsufficientFolders {
            get {
                return ResourceManager.GetString("ExploreFolder_ErrorExplanationInsufficientFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: At least 2 subfolders representing the collections to synchronise must be present inside the selected folder with photos in them.
        /// </summary>
        internal static string ExploreFolder_ErrorExplanationInsufficientPhotos {
            get {
                return ResourceManager.GetString("ExploreFolder_ErrorExplanationInsufficientPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring folder &apos;{0}&apos;.
        /// </summary>
        internal static string ExploreFolder_ExploringMainFolder {
            get {
                return ResourceManager.GetString("ExploreFolder_ExploringMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring subfolder &apos;{0}&apos;.
        /// </summary>
        internal static string ExploreFolder_ExploringSubFolder {
            get {
                return ResourceManager.GetString("ExploreFolder_ExploringSubFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring folder OK.
        /// </summary>
        internal static string ExploreFolder_OKConclusion {
            get {
                return ResourceManager.GetString("ExploreFolder_OKConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Photo &apos;{0}&apos; has been ignored since it does not have Exif DateTime nor DateTimeOriginal.
        /// </summary>
        internal static string ExploreFolder_PhotoIgnored {
            get {
                return ResourceManager.GetString("ExploreFolder_PhotoIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} photos found in subfolder &apos;{1}&apos;..
        /// </summary>
        internal static string ExploreFolder_PhotosCount {
            get {
                return ResourceManager.GetString("ExploreFolder_PhotosCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} subfolders found.
        /// </summary>
        internal static string ExploreFolder_SubFolderCount {
            get {
                return ResourceManager.GetString("ExploreFolder_SubFolderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder will be ignored..
        /// </summary>
        internal static string ExploreFolder_SubFolderIgnored {
            get {
                return ResourceManager.GetString("ExploreFolder_SubFolderIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: found {0} subsubfolders in subfolder &apos;{1}&apos;, they will not be processed.
        /// </summary>
        internal static string ExploreFolder_SubSubFolderIgnored {
            get {
                return ResourceManager.GetString("ExploreFolder_SubSubFolderIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Generic_ButtonNext {
            get {
                return ResourceManager.GetString("Generic_ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string Generic_ButtonPrev {
            get {
                return ResourceManager.GetString("Generic_ButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted date/time.
        /// </summary>
        internal static string Generic_CorrectedDateTime {
            get {
                return ResourceManager.GetString("Generic_CorrectedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string Generic_Correction {
            get {
                return ResourceManager.GetString("Generic_Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string Generic_Day {
            get {
                return ResourceManager.GetString("Generic_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        internal static string Generic_Hour {
            get {
                return ResourceManager.GetString("Generic_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        internal static string Generic_Minute {
            get {
                return ResourceManager.GetString("Generic_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no correction.
        /// </summary>
        internal static string Generic_NoCorrection {
            get {
                return ResourceManager.GetString("Generic_NoCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOK.
        /// </summary>
        internal static string Generic_NOK {
            get {
                return ResourceManager.GetString("Generic_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original date/time.
        /// </summary>
        internal static string Generic_OriginalDateTime {
            get {
                return ResourceManager.GetString("Generic_OriginalDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        internal static string Generic_Second {
            get {
                return ResourceManager.GetString("Generic_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Screen1_ButtonBrowse {
            get {
                return ResourceManager.GetString("Screen1_ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and check folder content.
        /// </summary>
        internal static string Screen1_ButtonImport {
            get {
                return ResourceManager.GetString("Screen1_ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking and listing selected folder content ongoing. Please wait ....
        /// </summary>
        internal static string Screen1_CheckingFolderContent {
            get {
                return ResourceManager.GetString("Screen1_CheckingFolderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photos folder.
        /// </summary>
        internal static string Screen1_Header {
            get {
                return ResourceManager.GetString("Screen1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder ....
        /// </summary>
        internal static string Screen1_HintBrowseFolder {
            get {
                return ResourceManager.GetString("Screen1_HintBrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect folder choice.
        /// </summary>
        internal static string Screen1_LabelIncorrect {
            get {
                return ResourceManager.GetString("Screen1_LabelIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        internal static string Screen1_MsgBoxDirectoryNotExist {
            get {
                return ResourceManager.GetString("Screen1_MsgBoxDirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select primary camera folder.
        /// </summary>
        internal static string Screen2_Header {
            get {
                return ResourceManager.GetString("Screen2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a camera folder which date/time is OK or for which you want to apply an ad-hoc time adjustment.
        /// </summary>
        internal static string Screen2_Introduction {
            get {
                return ResourceManager.GetString("Screen2_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending album is synchronized.
        /// </summary>
        internal static string Screen3_ButtonPendingSync {
            get {
                return ResourceManager.GetString("Screen3_ButtonPendingSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize pending camera folders.
        /// </summary>
        internal static string Screen3_Header {
            get {
                return ResourceManager.GetString("Screen3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a synchronized album and a pending album. Then search for two photos taken at the same time (or set the adujsted date/time of a given photo manually) and validate synchronization..
        /// </summary>
        internal static string Screen3_Introduction {
            get {
                return ResourceManager.GetString("Screen3_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Albums.
        /// </summary>
        internal static string Screen3_PendingAlbums {
            get {
                return ResourceManager.GetString("Screen3_PendingAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized Albums.
        /// </summary>
        internal static string Screen3_SyncAlbums {
            get {
                return ResourceManager.GetString("Screen3_SyncAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 euros.
        /// </summary>
        internal static string Screen4_ButtonDonate5Euros {
            get {
                return ResourceManager.GetString("Screen4_ButtonDonate5Euros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free amount.
        /// </summary>
        internal static string Screen4_ButtonDonateFreeAmount {
            get {
                return ResourceManager.GetString("Screen4_ButtonDonateFreeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go !.
        /// </summary>
        internal static string Screen4_ButtonGo {
            get {
                return ResourceManager.GetString("Screen4_ButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Screen4_ButtonQuit {
            get {
                return ResourceManager.GetString("Screen4_ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logs.
        /// </summary>
        internal static string Screen4_ButtonShowLogs {
            get {
                return ResourceManager.GetString("Screen4_ButtonShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string Screen4_ColCorrection {
            get {
                return ResourceManager.GetString("Screen4_ColCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename prefix.
        /// </summary>
        internal static string Screen4_ColFilenamePrefix {
            get {
                return ResourceManager.GetString("Screen4_ColFilenamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        internal static string Screen4_ColFolderName {
            get {
                return ResourceManager.GetString("Screen4_ColFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed - {0} photos date/time corrected.
        /// </summary>
        internal static string Screen4_CompletedText {
            get {
                return ResourceManager.GetString("Screen4_CompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - unfortunately, {1} photos are in error..
        /// </summary>
        internal static string Screen4_CompletedTextForErrors {
            get {
                return ResourceManager.GetString("Screen4_CompletedTextForErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed ! {0}..
        /// </summary>
        internal static string Screen4_ConversionFailed {
            get {
                return ResourceManager.GetString("Screen4_ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have corrected a total of {0} photos from {1} cameras..
        /// </summary>
        internal static string Screen4_FinalWords_Part1 {
            get {
                return ResourceManager.GetString("Screen4_FinalWords_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy the software, please support us and spread the word..
        /// </summary>
        internal static string Screen4_FinalWords_Part2 {
            get {
                return ResourceManager.GetString("Screen4_FinalWords_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply correction to photos.
        /// </summary>
        internal static string Screen4_Header {
            get {
                return ResourceManager.GetString("Screen4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following time corrections will be applied to the pictures of each folders.
        /// </summary>
        internal static string Screen4_Introduction {
            get {
                return ResourceManager.GetString("Screen4_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Screen4_LabelDonate {
            get {
                return ResourceManager.GetString("Screen4_LabelDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are not activated. Please contact Photo Time Sync support (phototimesync@oviles.info)..
        /// </summary>
        internal static string Screen4_LogsAreNotActivated {
            get {
                return ResourceManager.GetString("Screen4_LogsAreNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcting photos date/time - {0}%.
        /// </summary>
        internal static string Screen4_ProgressText {
            get {
                return ResourceManager.GetString("Screen4_ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename photos so that they can be sorted alphabeticaly.
        /// </summary>
        internal static string Screen4_RenamePhotosCheckbox {
            get {
                return ResourceManager.GetString("Screen4_RenamePhotosCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character &apos;_&apos; is not allowed in filename prefix..
        /// </summary>
        internal static string Screen4_UnderscoreNotAllowed {
            get {
                return ResourceManager.GetString("Screen4_UnderscoreNotAllowed", resourceCulture);
            }
        }
    }
}
